# Generated by Django 3.2.3 on 2021-05-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genres',
            new_name='genre_ids',
        ),
    ]
